project:
  type: website
  resources:
    - "pdfs/"
    
website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: Team
      - href: publications.qmd
        text: Publications

format:
  html:
    theme: cosmo
    toc: false
    link-external-newwindow: true