---
title: "Publications"
toc: true
---
Note: <u>Underlined</u> authors indicate my Ph.D. students and postdocs.


## 2026

**Lstibůrek, M.**, Bittner, V., Solvin, T.M., Korecký, J., and Steffenrem A. (2026). Identifying optimal sets of individuals under a pairwise genomic relationship threshold for breeding and conservation. *Genetics*, 233(2), iyag095.\
⭐ **Featured Article**
[ [Journal](https://doi.org/10.1093/genetics/iyag095) ]  [ [GitHub Code](https://github.com/mlstiburek/Selection_unrelated) ]

<u>Sagariya, C.</u>, Bittner, V., Pook, T., Roy, A., and **Lstibůrek, M.** (2026). Impact of erroneous marker data on the accuracy of narrow-sense heritability. *Genetics*, 232(1), iyaf230. 
[[Journal]](https://doi.org/10.1093/genetics/iyaf230)  [[PDF]](../pdfs/sagariya_2026.pdf){target="_blank"} [[GitHub Code]](https://github.com/mlstiburek/genotyping_error_heritability)

Štěpánová, K., Lhotáková, Z., <u>Neuwirthová, E.</u>, Kupková, L., Červená, L., Raasch, F., Potůčková, M., Stejskal, J., Čepl, J., Campbell, P., **Lstibůrek, M.**, Albrechtová, J. (2026). Scots pine seedlings of lowland and upland 
ecotypes respond differently to drought detected by needle functional traits and spectral reflectance. *BMC Plant Biology*, 26, 261. 
[[Journal]](https://doi.org/10.1186/s12870-025-08019-y)  [[PDF]](../pdfs/Stepanova_2026.pdf){target="_blank"}

<u>Neuwirthová, E.</u>, Chuchlík, J., Pikl, M., Lhotáková, Z., Kashkan, I., Panzarová, K., Stejskal, J., Albrechtová, J., **Lstibůrek, M.**, Čepl, J.  (2026). Overcoming difficulties in segmentation of hyperspectral plant images with small projection areas using machine learning. *Scientific Reports*, 16, 4325. 
[[Journal]](https://doi.org/10.1038/s41598-025-31952-9)  [[PDF]](../pdfs/Neuwirthova_2026.pdf){target="_blank"}

## 2025

Jeon, K., <u>Kim, Y.</u>, Kang, K.S., <u>Sagariya, C.</u>, **Lstibůrek, M.** (2025). Incorporating specific combining ability into selective seed harvest significantly increases genetic gain: a simulation study on Korean red pine. *Tree Genetics & Genomes*, 21(5), 26.
[[Journal]](https://doi.org/10.1007/s11295-025-01710-z)  [[GitHub Code]](https://github.com/mlstiburek/selective_seed_harvest)

<u>Sagariya, C.</u>, Steffenrem, A., Gezan, S., Pook, T., García-Gil, R., Kastally, C.,  Pyhäjärvi, T., **Lstibůrek, M.** (2025). The heritability accuracy in forest tree breeding programs relying on random mating. *Scandinavian Journal of Forest Research*, 40(5-6), 292-302.
[[Journal]](https://doi.org/10.1080/02827581.2025.2530427) [[PDF]](../pdfs/sagariya_2025.pdf){target="_blank"}

<u>Chludil, D.</u>, Čepl, J., Steffenrem, A., Stejskal, J., <u>Sagariya, C.</u>, Pook, T.,  Schueler, S., Korecký, J., Almqvist, C., Chakraborty, D., Berlin, M., **Lstibůrek, M.** (2025). A pollen-based assisted migration for rapid forest adaptation. *Global Change Biology*, 31(1), e70014.
[[Journal]](https://doi.org/10.1111/gcb.70014) [[PDF]](../pdfs/Chludil_2025_1.pdf){target="_blank"}

<u>Chludil, D.</u>, Almquist, C., Berlin, M., Steffenrem, A., McKeand, S.E., Korecký, J., Stejskal, J., Čepl, J., Isik, F., Chakraborty, D., Schueler, S., Pook, T., <u>Sagariya, C.</u>, **Lstibůrek, M.** (2025). Alleviating the concerns about pollen-based assisted migration. *Global Change Biology*, 31(6), e70262.
[[Journal]](https://doi.org/10.1111/gcb.70262) [[PDF]](../pdfs/Chludil_2025_2.pdf){target="_blank"}

<u>Neuwirthová, E.</u>, Stejskal, J., Lhotáková, Z., Korecký, J., Čepl, J., Nikodem, A., Panzarová, K., Albrechtová, J., **Lstibůrek, M.** (2025). Drought response and genetic variation in Scots pine seedlings' provenances: insights from high-throughput phenotyping for climate-resilient forestry. *Evolutionary Applications*, 18, e70157.
[[Journal]](https://doi.org/10.1111/eva.70157) [[PDF]](../pdfs/Neuwirthova_2025_1.pdf){target="_blank"}

Provazník, D., Stejskal, J., Lhotáková, Z., Čepl, J., <u>Neuwirthová, E.</u>, Nofrizal, A.Y., Korecký, J., Červená, L., Kupková, L., Klápště, J., Hansen, J.K., Gezan, S.A., Campbell, P., **Lstibůrek, M.**, Albrechtová, J. (2025). Needle‐ and canopy‐level genetic variation in Scots pine (Pinus sylvestris L.) revealed by hyperspectral phenotyping across sites and seasons. *Evolutionary Applications*, 18, e70176.
[[Journal]](https://doi.org/10.1111/eva.70176) [[PDF]](../pdfs/Provaznik_2025.pdf){target="_blank"}

## 2024

Chakraborty, D., Ciceu, A., Ballian, D., Benito, G.M., Bolte, A., Bozic, G., Buchacher, R., Čepl, J., Cremer, E., Ducousso, A., Gaviria, J., George, J.P., Hardtke, A., Ivankovic, M., Klisz, M., Kowalczyk, J., Kremer, A., **Lstibůrek, M.**, Longauer, R., Mihai, G., Nagy, L., Petkova, K., Popov, E., Schirmer, R., Skrøppa, T., Solvin, T.M., Steffenrem, A., Stejskal, J., Stojnic, S., Volmer, K., Schueler, S. (2024). Assisted tree migration can preserve the European forest carbon sink under climate change. *Nature Climate Change*, 14(8), 845-852.
[[Journal]](https://doi.org/10.1038/s41558-024-02080-5) [[PDF]](../pdfs/Chakraborty_2024.pdf){target="_blank"}

## 2023

**Lstibůrek, M.**, García-Gil, R., Steffenrem, A. (2023). Rolling front landscape breeding. *Annals of Forest Science*, 80, 36.
[[Journal]](https://doi.org/10.1186/s13595-023-01203-w) [[PDF]](../pdfs/Lstiburek_2023.pdf){target="_blank"}

<u>Poupon, V.</u>, Gezan, S.A., Schueler, S., **Lstibůrek, M.** (2023). Genotype x environment interaction and climate sensitivity in growth and wood density of European larch.  *Forest Ecology and Management*, 545, 121259.
[[Journal]](https://doi.org/10.1016/j.foreco.2023.121259) [[PDF]](../pdfs/Poupon_2023.pdf){target="_blank"}

Stejskal, J., Čepl, J., <u>Neuwirthová, E.</u>, Akinyemi O.O., Chuchlík, J., Provazník, D., Keinänen, M., Campbell, P., Albrechtová, J., **Lstibůrek, M.**, Lhotáková, Z. (2023). Making the genotypic variation visible: hyperspectral phenotyping in Scots pine seedlings. *Plant Phenomics*, 5, 0111.
[[Journal]](https://doi.org/10.34133/plantphenomics.0111) [[PDF]](../pdfs/Stejskal_2023.pdf){target="_blank"}

## 2022

<u>Chaloupková, K.</u>, **Lstibůrek, M.** (2022). Spatial optimization of genetic thinning in seed orchards. *Annals of Forest Science*, 79, 37.
[[Journal]](https://doi.org/10.1186/s13595-022-01158-4)  [[PDF]](../pdfs/Chaloupkova_2022.pdf){target="_blank"}

Stejskal, J., Klápště, J., Čepl, J., El-Kassaby, Y.A., **Lstibůrek, M.** (2022). Effect of clonal testing on the efficiency of genomic evaluation in forest tree breeding. *Scientific Reports*, 12, 3033.
[[Journal]](https://doi.org/10.1038/s41598-022-06952-8)  [[PDF]](../pdfs/Stejskal_2022.pdf){target="_blank"}

## 2021

Korecký, J., Čepl, J., Stejskal, J., Faltinová, Z., Dvořák, J., **Lstibůrek, M.**, El-Kassaby, Y.A. (2021). Genetic diversity of Norway spruce ecotypes assessed by GBS-derived SNPs. *Scientific Reports*, 11, 23119.
[[Journal]](https://doi.org/10.1038/s41598-021-02545-z)  [[PDF]](../pdfs/Korecky_2021.pdf){target="_blank"}

<u>Poupon, V.</u>, Chakraborty, D., Stejskal, J., Konrad, H., Schueler, S., **Lstibůrek, M.** (2021). Accelerating adaptation of forest trees to climate change using individual tree response functions. *Frontiers in Plant Science*, 23, 758221.
[[Journal]](https://doi.org/10.3389/fpls.2021.758221)  [[PDF]](../pdfs/Poupon_2021.pdf){target="_blank"}

Hazarika, R., Bolte, A., Bednarova, D., Chakraborty, D., Gaviria, J., Kanzian, M., Kowalczyk, J., Lackner, M., **Lstibůrek, M.**, Longauer, R., Nagy, L., Tomášková, I., Schueler, S. (2021). Correction to: Multi-actor perspectives on afforestation and reforestation strategies in Central Europe under climate change. *Annals of Forest Science*, 78, 71.
[[Journal]](https://doi.org/10.1007/s13595-021-01088-7)  [[PDF]](../pdfs/Hazarika_2021_1.pdf){target="_blank"}

Hazarika, R., Bolte, A., Bednarova, D., Chakraborty, D., Gaviria, J., Kanzian, M., Kowalczyk, J., Lackner, M., **Lstibůrek, M.**, Longauer, R., Nagy, L., Tomášková, I., Schueler, S. (2021). Multi-actor perspectives on afforestation and reforestation strategies in Central Europe under climate change. *Annals of Forest Science*, 78, 60.
[[Journal]](https://doi.org/10.1007/s13595-021-01044-5)  [[PDF]](../pdfs/Hazarika_2021.pdf){target="_blank"}

## 2020

**Lstibůrek, M.**, Schueler, S., El-Kassaby, Y.A., Hodge, G.R., Stejskal, J., Korecký, J., Škorpík, P., Konrad, H., Geburek, T. (2020). In situ genetic evaluation of European larch across climatic regions using marker-based pedigree reconstruction. *Frontiers in Genetics*, 11, 28.
[[Journal]](https://doi.org/10.3389/fgene.2020.00028)  [[PDF]](../pdfs/Lstiburek_2020.pdf){target="_blank"}

Bínová, Z., Korecký, J., Dvořák, J., Bílý, J., Zádrapová, D., Jansa, V., **Lstibůrek, M.** (2020). Genetic structure of Norway spruce ecotypes studied by SSR markers. *Forests*, 11(1), 110.
[[Journal]](https://doi.org/10.3390/f11010110)  [[PDF]](../pdfs/Binova_2020.pdf){target="_blank"}

## 2019

<u>Chaloupková, K.</u>, Stejskal, J., El-Kassaby, Y.A., Frampton, J., **Lstibůrek, M.** (2019). Current advances in seed orchard layouts: two case studies in conifers. *Forests*, 10(2), 93.
[[Journal]](https://doi.org/10.3390/f10020093)  [[PDF]](../pdfs/Chaloupkova_2019.pdf){target="_blank"}

## 2018

**Lstibůrek, M.**, Bittner, V., Hodge, G.H., Picek, J., Mackay, T.F.C. (2018). Estimating realized heritability in panmictic populations. *Genetics*, 208(1), 89-95. 
[[Journal]](https://doi.org/10.1534/genetics.117.300508)  [[PDF]](../pdfs/Lstiburek_2018.pdf){target="_blank"} [[GitHub Code]](https://github.com/mlstiburek/Computer-code-realized-heritability)

Stejskal, J., **Lstibůrek, M.**, Klápště, J., Čepl, J., El-Kassaby, Y.A. (2018). Effect of genomic prediction on response to selection in forest tree breeding. *Tree Genetics & Genomes*, 14, 74.
[[Journal]](https://doi.org/10.1007/s11295-018-1283-8)  [[PDF]](../pdfs/Stejskal_2018.pdf){target="_blank"}

Čepl, J., Stejskal, J., Lhotáková, Z., Holá, D., Korecký, J., **Lstibůrek, M.**, Tomášková, I., Kočová, M., Rothová, O., Palovská, M., Hejtmánek, J., Krejzková, A., Gezan, S., Whetten, R., Albrechtová, J. (2018). Heritable variation in needle spectral reflectance of Scots pine (Pinus sylvestris L.) peaks in red edge. *Remote Sensing of Environment*, 219: 89-98.
[[Journal]](https://doi.org/10.1016/j.rse.2018.10.001)

## 2017

**Lstibůrek, M.**, El-Kassaby, Y.A., Skrøppa, T., Hodge, G.R.,  Sønstebø, J.H., Steffenrem, A. (2017). Dynamic gene-resource landscape management of Norway spruce: combining utilization and conservation. *Frontiers in Plant Science*, 8, 1810.
[[Journal]](https://doi.org/10.3389/fpls.2017.01810)  [[PDF]](../pdfs/Lstiburek_2017.pdf){target="_blank"}

<u>Korecký, J.</u>, Bílý, J., Sedlák, P., **Lstibůrek, M.** (2017). Innovative multiplex and its evaluation for effective genotyping of wild cherry. *Silvae Fennica*, 51(3), 5644.
[[Journal]](https://doi.org/10.14214/sf.5644)  [[PDF]](../pdfs/Korecky_2017.pdf){target="_blank"}

## 2016

<u>Chaloupková, K.</u>, Stejskal, J., El-Kassaby, Y.A., **Lstibůrek, M.** (2016). Optimum neighborhood seed orchard design. *Tree Genetics & Genomes*, 12, 105.
[[Journal]](https://doi.org/10.1007/s11295-016-1067-y)  [[PDF]](../pdfs/Chaloupkova_2016.pdf){target="_blank"}

Čepl, J., Holá, D., Stejskal, J., <u>Korecký, J.</u>, Kočová, M., Lhotáková, Z., Tomášková, I., Palovská, M., Rothová, O., Whetten, R.W., <u>Kaňák, J.</u>, Albrechtová, J., **Lstibůrek, M.** (2016). Genetic variability and heritability of chlorophyll a fluorescence parameters in Scots pine (Pinus sylvestris L.). *Tree Physiology*, 36(7): 883-895.
[[Journal]](https://doi.org/10.1093/treephys/tpw028)

## 2015

**Lstibůrek, M.**, Hodge, G.R., Lachout, P. (2015). Uncovering genetic information from commercial forest plantations—making up for lost time using “Breeding without Breeding”. *Tree Genetics & Genomes*, 11, 55.
[[Journal]](https://doi.org/10.1007/s11295-015-0881-y)  [[PDF]](../pdfs/Lstiburek_2015_1.pdf){target="_blank"}

**Lstibůrek, M.**, Stejskal, J., Misevicius, A., <u>Korecký, J.</u>, El-Kassaby, Y.A. (2015). Expansion of the minimum-inbreeding seed orchard design to operational scale. *Tree Genetics & Genomes*, 11, 12.
[[Journal]](https://doi.org/10.1007/s11295-015-0842-5)  [[PDF]](../pdfs/Lstiburek_2015.pdf){target="_blank"}

## 2014

<u>Korecký, J.</u>, **Lstibůrek, M.**, El-Kassaby, Y.A. (2014). Congruence between theory and practice: reduced contamination rate following phenotypic pre-selection within the Breeding-without-breeding framework. *Scandinavian Journal of Forest Research*, 29(6), 552-554.
[[Journal]](https://doi.org/10.1080/02827581.2014.945616)

El-Kassaby, Y.A., Fayed, M., Klápště, J., **Lstibůrek, M.** (2014). Randomized, replicated, staggered clonal-row (R2SCR) seed orchard design. *Tree Genetics & Genomes*, 10, 555-563.
[[Journal]](https://doi.org/10.1007/s11295-014-0703-7)  [[PDF]](../pdfs/ElKassaby_2014.pdf){target="_blank"}

Klápště, J., **Lstibůrek, M.**, El-Kassaby, Y.A. (2014). Estimates of genetic parameters and breeding values
from western larch open-pollinated families using marker-based relationship. *Tree Genetics & Genomes*, 10, 241-249.
[[Journal]](https://doi.org/10.1007/s11295-013-0673-1)  [[PDF]](../pdfs/Korecky_2013.pdf){target="_blank"}

## 2013

<u>Korecký, J.</u>, Klápště, J., **Lstibůrek, M.**, Kobliha, J., Nelson, D.C., El-Kassaby Y.A. (2013). Comparison of genetic parameters from marker-based relationship, sibship, and combined models in Scots pine multi-site open-pollinated tests. *Tree Genetics & Genomes*, 9, 1227-1235.
[[Journal]](https://doi.org/10.1007/s11295-013-0630-z)  [[PDF]](../pdfs/Korecky_2013.pdf){target="_blank"} 

Kobliha, J., Stejskal, J., **Lstibůrek, M.**, Marušák, R., Slávik, M. (2013). Selection of European larch provenances based on productivity and economic values. *Journal of Forest Science*, 59(11), 424-435.
[[PDF]](../pdfs/Kobliha_2013_1.pdf){target="_blank"}

Kobliha, J., Stejskal, J., **Lstibůrek, M.**, Typta, J., Tomášková, I., Jakubův, P. (2013). Testing of hybrid progenies and various species of genus Abies for forestry, decorating horticulture and Christmas tree production. *Acta Scientiarum Polonorum, Hortorum Cultus*, 12(4), 85-94.
[[Journal]](https://czasopisma.up.lublin.pl/asphc/article/view/2916)  [[PDF]](../pdfs/Kobliha_2013.pdf){target="_blank"}

## 2012

Funda, T., **Lstibůrek, M.**, Klápště, J., El-Kassaby, Y.A. (2012). Optimization of genetic gain and diversity in seed orchard crops considering variation in seed germination. *Scandinavian Journal of Forest Research*, 27(8), 787-793.
[[Journal]](https://doi.org/10.1080/02827581.2012.686627)

**Lstibůrek, M.**, Klápště, J., Kobliha, J., El-Kassaby, Y.A. (2012). Breeding without breeding: effect of gene flow on fingerprinting effort. *Tree Genetics & Genomes*, 8, 873-877.
[[Journal]](https://doi.org/10.1007/s11295-012-0472-0)  [[PDF]](../pdfs/Lstiburek_2012.pdf){target="_blank"}

## 2011

El-Kassaby, Y.A., Cappa, E.P., Liewlaksaneeyanawin, C., Klápště, J.,  **Lstibůrek, M.** (2011). Breeding without breeding: is a complete pedigree necessary for efficient breeding? *PLOS One*, 6(10), e25737.
[[Journal]](https://doi.org/10.1371/journal.pone.0025737)  [[PDF]](../pdfs/ElKassaby_2011.pdf){target="_blank"}

**Lstibůrek, M.**, Ivanková, K., Kadlec, J., Kobliha, J., Klápště, J., El-Kassaby Y.A. (2011). Breeding without breeding: minimum fingerprinting effort with respect to the effective population size. *Tree Genetics & Genomes*, 7, 1069-1078.
[[Journal]](https://doi.org/10.1007/s11295-011-0395-1)  [[PDF]](../pdfs/Lstiburek_2011.pdf){target="_blank"}

Cappa, E.P., **Lstibůrek, M.**, Yanchuk, A.D., El-Kassaby, Y.A. (2011). Two-dimensional penalized splines via Gibbs sampling to account for spatial variability in forest genetic trials with small amount of information available. *Silvae Genetica*, 60(1), 25-35.
[[Journal]](https://reference-global.com/article/10.1515/sg-2011-0004)  [[PDF]](../pdfs/Cappa_2011.pdf){target="_blank"}

## 2010

**Lstibůrek, M.**, El-Kassaby, Y.A. (2010). Minimum-inbreeding seed orchard design. *Genetics Research*, 56(6), 603-608.
[[Journal]](https://doi.org/10.1093/forestscience/56.6.603)  [[PDF]](../pdfs/Lstiburek_2010.pdf){target="_blank"}

## 2009
El-Kassaby, Y., **Lstibůrek, M.** (2009). Breeding without breeding. *Genetics Research*, 91(2), 111-120.
[[Journal]](https://doi.org/10.1017/S001667230900007X)  [[PDF]](../pdfs/Lstiburek_2009.pdf){target="_blank"}

Funda, T., **Lstibůrek, M.**, Lachout, P., El-Kassaby, Y. (2009). Optimization of combined genetic gain and diversity for collection and deployment of seed orchard crops. *Tree Genetics & Genomes*, 5, 583-593.
[[Journal]](https://doi.org/10.1007/s11295-009-0211-3)  [[PDF]](../pdfs/Funda_2009.pdf){target="_blank"}

<u>Kaňák, J.</u>, Klápště, J., **Lstibůrek, M.** (2009). Initial evaluation of seed orchards of Scots pine in the Western Czech Republic. *Zprávy lesnického výzkumu (ZLV)*, 54(3), 189-204. 
[[PDF]](../pdfs/Kanak_2009.pdf){target="_blank"}

## 2007
Klápště, J., **Lstibůrek, M.**, Kobliha, J. (2007). Initial evaluation of half-sib progenies of Norway spruce using the best linear unbiased prediction. *Journal of Forest Science*, 53(2), 41-46.
[[PDF]](../pdfs/Lstiburek_2007_1.pdf){target="_blank"}

Hajnala, M., **Lstibůrek, M.**, Kobliha, J. (2007). First evaluation of growth parameters in clonal test
with wild cherry. *Journal of Forest Science*, 53(2), 57-65.
[[PDF]](../pdfs/Lstiburek_2007_2.pdf){target="_blank"}

Funda, T., **Lstibůrek, M.**, Klápště, J., Permedlová, I., Kobliha, J. (2007). Addressing spatial variability in provenance experiments exemplified in two trials with black spruce. *Journal of Forest Science*, 53(2), 47-56.
[[PDF]](../pdfs/Lstiburek_2007_3.pdf){target="_blank"}

## 2006
**Lstibůrek, M.**, Mullin, T.J., El-Kassaby, Y. (2006). The impact of differential success of somatic embryogenesis on the outcome of clonal forestry programs. I. Initial comparison under multitrait selection. *Canadian Journal of Forest Research*, 36(6), 1376-1384.
[[Journal]](https://doi.org/10.1139/x06-036)  [[PDF]](../pdfs/Lstiburek_2006.pdf){target="_blank"}

## 2005
**Lstibůrek, M.**, Mullin, T.J., Mackay, T.F.C., Huber, D., Li, B. (2005). Positive assortative mating with family size as a function of predicted parental breeding values. *Genetics*, 171(3), 1311-1320.
[[Journal]](https://doi.org/10.1534/genetics.105.041723)  [[PDF]](../pdfs/Lstiburek_2005.pdf){target="_blank"}

**Lstibůrek, M.** (2005). *Population response to positive assortative mating in forest tree breeding.* Ph.D. Dissertation, North Carolina State University. 
[[NCSU Library]](http://www.lib.ncsu.edu/resolver/1840.16/3821)

## 2004

**Lstibůrek, M.**, Mullin, T.J., Lindgren, D., Rosvall, O. (2004). Open-nucleus breeding strategies compared with population-wide positive assortative mating. II. Unequal distribution of testing effort. *Theoretical and Applied Genetics*, 109(6), 1169-1177.
[[Journal]](https://doi.org/10.1007/s00122-004-1737-2)  [[PDF]](../pdfs/Lstiburek_2004_2.pdf){target="_blank"} 

**Lstibůrek, M.**, Mullin, T.J., Lindgren, D., Rosvall, O. (2004). Open-nucleus breeding strategies compared with population-wide positive assortative mating. I. Equal distribution of testing effort. *Theoretical and Applied Genetics*, 109(6), 1196-1203.
[[Journal]](https://doi.org/10.1007/s00122-004-1746-1)  [[PDF]](../pdfs/Lstiburek_2004_1.pdf){target="_blank"}